apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  namespace: sa-p5
  labels:
    app: movies
    app.kubernetes.io/name: movies
    app.kubernetes.io/part-of: sa-p5
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
        app.kubernetes.io/name: movies
        app.kubernetes.io/part-of: sa-p5
    spec:
      containers:
        - name: movies
          image: docker.io/zenthic22/movies:c4b58f6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "mysql.sa-p5.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "movies_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret     # nombre del Secret
                  key: MYSQL_PASSWORD    # clave dentro del Secret
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }