CREATE DATABASE IF NOT EXISTS cron_db;

USE cron_db;

CREATE TABLE IF NOT EXISTS cron_events (
    id INT PRIMARY KEY AUTO_INCREMENT,
    carnet VARCHAR(20) NOT NULL,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);