apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors
  namespace: sa-p5
  labels:
    app: actors
    app.kubernetes.io/name: actors
    app.kubernetes.io/part-of: sa-p5
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: actors
  template:
    metadata:
      labels:
        app: actors
        app.kubernetes.io/name: actors
        app.kubernetes.io/part-of: sa-p5
    spec:
      containers:
        - name: actors
          image: docker.io/zenthic22/actors:c4b58f6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_HOST
              value: "mysql.sa-p5.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "actors_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"