apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: actors
  namespace: sa-p5
  labels:
    app: actors
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: actors
  minReplicas: 2   # opcional: 2 para HA
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80