apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: sa-p5
  labels:
    app: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 999           # mysql user/group en la imagen oficial suele ser 999
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            # NOTA: No definimos MYSQL_DATABASE/USER/PASSWORD porque inicializamos vía SQL
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            tcpSocket: { port: 3306 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 3306 }
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: init-sql
          configMap:
            name: mysql-init
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: mysql
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName: <deja que Kubespray use la default en la nube>
        resources:
          requests:
            storage: 10Gi