apiVersion: v1
kind: Namespace
metadata:
  name: sa-p5
  labels:
    app.kubernetes.io/name: sa-p5
    app.kubernetes.io/part-of: sa-p5
    app.kubernetes.io/managed-by: kubectl
    environment: cloud
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: sa-p5
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: baseline
  namespace: sa-p5
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    pods: "50"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: sa-p5
spec:
  podSelector: {}
  policyTypes: ["Ingress","Egress"]