apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-policy
  namespace: sa-p5
spec:
  podSelector:
    matchLabels:
      app: gateway
  policyTypes: ["Ingress","Egress"]
  ingress:
    # 1) Permite tráfico externo (NodePort -> pod) al puerto 4001
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 4001
    # 2) (Opcional) Mantén permiso desde el Ingress Controller por si lo reactivas
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
      ports:
        - protocol: TCP
          port: 4001
  egress:
    # Microservicios internos
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sa-p5
          podSelector:
            matchExpressions:
              - key: app
                operator: In
                values: ["actors","movies","reviews","users"]
      ports:
        - { protocol: TCP, port: 4000 }
        - { protocol: TCP, port: 3000 }
        - { protocol: TCP, port: 5002 }
        - { protocol: TCP, port: 5003 }
    # DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }