apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-policy
  namespace: sa-p5
spec:
  podSelector:
    matchLabels:
      app: gateway
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
        - podSelector: {}  # opcional, para pruebas internas en el NS
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 4001
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sa-p5
          podSelector:
            matchExpressions:
              - key: app
                operator: In
                values: ["actors","movies","reviews","users"]
      ports:
        - { protocol: TCP, port: 3000 }
        - { protocol: TCP, port: 4000 }
        - { protocol: TCP, port: 5002 }
        - { protocol: TCP, port: 5003 }
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }