apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: sa-p5
  labels: { app: gateway }
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - name: http
      port: 4001
      targetPort: http