apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: sa-p5
  labels:
    app: users
    app.kubernetes.io/name: users
    app.kubernetes.io/part-of: sa-p5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        app.kubernetes.io/name: users
        app.kubernetes.io/part-of: sa-p5
    spec:
      containers:
        - name: users
          image: docker.io/zenthic22/users:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: DB_HOST
              value: "mysql.sa-p5.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "users_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "300m", memory: "256Mi" }
      imagePullSecrets:
        - name: regcred