apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: users
  namespace: sa-p5
  labels:
    app: users
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users
  minReplicas: 2   # opcional: 2 para alta disponibilidad
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80