apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reviews
  namespace: sa-p5
  labels:
    app: reviews
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reviews
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80