apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: sa-p5
  labels:
    app: reviews
spec:
  selector:
    app: reviews
  ports:
    - name: http
      port: 5002
      targetPort: http
  type: ClusterIP