name: CI/CD – SA P7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  REPO: zenthic22
  # Lista de microservicios (carpetas a construir)
  SERVICES: |
    gateway
    movies
    actors
    reviews
    users
    cronjob-runner

jobs:
  build_push:
    name: Build & Push Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (matrix-like loop)
        run: |
          set -euo pipefail
          TAG=${{ steps.vars.outputs.SHORT_SHA }}
          for svc in $SERVICES; do
            case "$svc" in
              cronjob-runner) ctx="cronjob-runner"; img="$REPO/cronjob";;
              *)               ctx="$svc";           img="$REPO/$svc";;
            esac
            echo "==> Building $REGISTRY/$img:{latest,$TAG} from $ctx"
            docker build -t $REGISTRY/$img:latest -t $REGISTRY/$img:$TAG $ctx
            docker push $REGISTRY/$img:latest
            docker push $REGISTRY/$img:$TAG
          done
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPO: ${{ env.REPO }}
          SERVICES: ${{ env.SERVICES }}

      - name: Export image tags (artifact)
        run: echo "${{ steps.vars.outputs.SHORT_SHA }}" > image_tag.txt

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt

  deploy_via_ssh:
    name: Deploy to K8s (via SSH on master)
    runs-on: ubuntu-latest
    needs: [build_push]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image tag
        uses: actions/download-artifact@v4
        with:
          name: image_tag
          path: .

      - name: Read tag
        id: tag
        run: echo "TAG=$(cat image_tag.txt)" >> $GITHUB_OUTPUT

      - name: Prepare deploy script
        run: |
          cat > deploy.sh <<'EOS'
          set -euo pipefail

          NS=sa-p5
          TAG="$1"

          echo "[*] kubectl context:"
          kubectl cluster-info || true

          echo "[*] Apply namespace first"
          kubectl apply -f k8s/namespace.yaml

          echo "[*] Apply app manifests"
          kubectl -n "$NS" apply -f k8s/mysql/
          kubectl -n "$NS" apply -f k8s/actors/
          kubectl -n "$NS" apply -f k8s/movies/
          kubectl -n "$NS" apply -f k8s/reviews/
          kubectl -n "$NS" apply -f k8s/users/
          kubectl -n "$NS" apply -f k8s/gateway/
          kubectl -n "$NS" apply -f k8s/cronjob/

          echo "[*] Patch images with immutable tag $TAG"
          kubectl -n "$NS" set image deploy/actors   actors=docker.io/${REPO}/actors:$TAG --record=true
          kubectl -n "$NS" set image deploy/movies   movies=docker.io/${REPO}/movies:$TAG --record=true
          kubectl -n "$NS" set image deploy/reviews  reviews=docker.io/${REPO}/reviews:$TAG --record=true
          kubectl -n "$NS" set image deploy/users    users=docker.io/${REPO}/users:$TAG --record=true
          kubectl -n "$NS" set image deploy/gateway  gateway=docker.io/${REPO}/gateway:$TAG --record=true

          echo "[*] Patch cronjob image"
          kubectl -n "$NS" patch cronjob/cron-insert --type='json' \
            -p="[{'op':'replace','path':'/spec/jobTemplate/spec/template/spec/containers/0/image','value':'docker.io/${REPO}/cronjob:$TAG'}]"

          echo "[*] Wait rollouts"
          kubectl -n "$NS" rollout status deploy/actors   --timeout=180s
          kubectl -n "$NS" rollout status deploy/movies   --timeout=180s
          kubectl -n "$NS" rollout status deploy/reviews  --timeout=180s
          kubectl -n "$NS" rollout status deploy/users    --timeout=180s
          kubectl -n "$NS" rollout status deploy/gateway  --timeout=180s

          echo "[*] Summary"
          kubectl -n "$NS" get pods,svc,ingress,hpa
          EOS
          chmod +x deploy.sh

      - name: Copy repo (k8s/ + script) to master
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            passphrase: ${{ secrets.SSH_PASSPHRASE }}
            port: 22
            source: "./k8s/**,deploy.sh"
            target: "/home/${{ secrets.SSH_USER }}/sa-p5/"

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          command_timeout: 30m
          envs: REPO
          script: |
            set -euo pipefail
            export REPO="${{ env.REPO }}"
            cd ~/sa-p5
            if [ ! -f ~/.kube/config ]; then
              mkdir -p ~/.kube
              sudo cat /etc/kubernetes/admin.conf > ~/.kube/config
              chmod 600 ~/.kube/config
            fi
            ./deploy.sh "${{ steps.tag.outputs.TAG }}"